#!/usr/bin/env python3
"""
CTCI Study Platform — Data Extraction, Validation & Bundler Tool
---------------------------------------------------------------
This Python automation script enables you to:
1. Validate all modular chapter data files (schema, required keys, quiz consistency).
2. Bundle modular chapter files (data/chapters/*.js) into the root data.js for the browser.
3. Generate new problem templates to expand your curriculum with zero AI hallucination.
4. Parse raw Markdown or problem dumps into structured problem objects.

Usage:
  python scripts/extract_or_expand_data.py --bundle
  python scripts/extract_or_expand_data.py --validate
  python scripts/extract_or_expand_data.py --new-problem --chapter 1 --title "Zero Matrix"
"""

import os
import sys
import json
import re
import argparse
from pathlib import Path

# Ensure UTF-8 output on Windows consoles
if sys.platform == "win32" and hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
CHAPTERS_DIR = DATA_DIR / "chapters"
OUTPUT_DATA_JS = BASE_DIR / "data.js"


def read_file(path: Path) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def write_file(path: Path, content: str) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def bundle_data():
    """Combines all modular files into a single production-ready data.js."""
    print("📦 Bundling modular data files into data.js...")
    
    tracks_code = read_file(DATA_DIR / "tracks.js")
    milestones_code = read_file(DATA_DIR / "milestones.js")
    
    # Clean export statements
    tracks_code = re.sub(r'if\s*\(\s*typeof module.*$', '', tracks_code, flags=re.DOTALL).strip()
    milestones_code = re.sub(r'if\s*\(\s*typeof module.*$', '', milestones_code, flags=re.DOTALL).strip()

    # Collect all chapters in order
    chapter_files = sorted(CHAPTERS_DIR.glob("chapter*.js"))
    if not chapter_files:
        print("❌ Error: No chapter files found in data/chapters/")
        sys.exit(1)
        
    chapters_content = []
    chapter_var_names = []
    
    for ch_file in chapter_files:
        content = read_file(ch_file)
        # Strip module.exports
        content = re.sub(r'if\s*\(\s*typeof module.*$', '', content, flags=re.DOTALL).strip()
        
        # Extract var name (e.g. chapter01)
        match = re.search(r'const\s+([a-zA-Z0-9_]+)\s*=', content)
        if match:
            var_name = match.group(1)
            chapter_var_names.append(var_name)
        chapters_content.append(content)

    joined_chapters = "\n\n".join(chapters_content)
    var_list = ", ".join(chapter_var_names)

    bundle_header = f"""/**
 * CTCI Study Platform — Master Bundled Data
 * AUTO-GENERATED via scripts/extract_or_expand_data.py --bundle
 * Do not edit this file directly. Edit files in data/chapters/ instead.
 */

// ── Chapter Modules ──────────────────────────────────────────
{joined_chapters}

// ── Chapters Array ───────────────────────────────────────────
const CHAPTERS = [
  {var_list}
];

// ── Learning Tracks ──────────────────────────────────────────
{tracks_code}

// ── Achievement Milestones ───────────────────────────────────
{milestones_code}

// ── Global & Node Export Compatibility ───────────────────────
if (typeof window !== "undefined") {{
  window.CHAPTERS = CHAPTERS;
  window.TRACKS = TRACKS;
  window.MILESTONES = MILESTONES;
}}

if (typeof module !== "undefined" && module.exports) {{
  module.exports = {{ CHAPTERS, TRACKS, MILESTONES }};
}}
"""
    write_file(OUTPUT_DATA_JS, bundle_header)
    print(f"✅ Successfully bundled {len(chapter_files)} chapters into {OUTPUT_DATA_JS} ({len(bundle_header)} bytes)")


def validate_data():
    """Validates structure and integrity of all chapters."""
    print("🔍 Validating modular chapter datasets...")
    chapter_files = sorted(CHAPTERS_DIR.glob("chapter*.js"))
    total_problems = 0
    total_quizzes = 0
    errors = []

    for ch_file in chapter_files:
        content = read_file(ch_file)
        # Check required keys
        for key in ["id:", "title:", "icon:", "description:", "concepts:", "problems:", "quiz:"]:
            if key not in content:
                errors.append(f"Missing '{key}' in {ch_file.name}")
        
        # Count problems
        prob_matches = re.findall(r'id:\s*"([0-9]+\.[0-9]+)"', content)
        quiz_matches = re.findall(r'question:\s*"', content)
        total_problems += len(prob_matches)
        total_quizzes += len(quiz_matches)
        print(f"  • {ch_file.name}: {len(prob_matches)} coding problems, {len(quiz_matches)} quiz questions")

    print(f"\n📊 Summary:")
    print(f"  - Chapters: {len(chapter_files)}")
    print(f"  - Total Interview Problems: {total_problems}")
    print(f"  - Total Quiz Questions: {total_quizzes}")

    if errors:
        print("❌ Validation failed with errors:")
        for e in errors:
            print(f"  - {e}")
        sys.exit(1)
    else:
        print("✅ All chapter files validated successfully!")


def generate_problem_template(chapter_num: int, title: str):
    """Outputs a standard problem template for manual or automated insertion."""
    template = {
        "id": f"{chapter_num}.X",
        "title": title,
        "banglaTitle": f"{title} (বাংলা শিরোনাম)",
        "difficulty": "Medium",
        "description": "সমস্যার বিবরণ বাংলায় লিখুন...",
        "examples": [
            {"input": "...", "output": "...", "explanation": "..."}
        ],
        "constraints": ["..."],
        "hints": [
            "💡 Hint 1: প্রথম ইঙ্গিত...",
            "💡 Hint 2: দ্বিতীয় ইঙ্গিত..."
        ],
        "approach": "সমাধানের যুক্তি ও পদ্ধতি বিস্তারিত বাংলায়...",
        "solutions": [
            {
                "language": "javascript",
                "code": f"function solve(input) {{\n  // কোড লিখুন\n}}",
                "explanation": "কোডের ব্যাখ্যা বাংলায়..."
            }
        ],
        "complexity": {
            "time": "O(n)",
            "space": "O(1)"
        }
    }
    print(json.dumps(template, indent=2, ensure_ascii=False))


def main():
    parser = argparse.ArgumentParser(description="CTCI Data Management & Extraction Script")
    parser.add_argument("--bundle", action="store_true", help="Bundle modular files into data.js")
    parser.add_argument("--validate", action="store_true", help="Validate all chapter data files")
    parser.add_argument("--new-problem", action="store_true", help="Generate a new problem template")
    parser.add_argument("--chapter", type=int, default=1, help="Chapter number for new problem")
    parser.add_argument("--title", type=str, default="New Problem", help="Title for new problem")

    args = parser.parse_args()

    if args.bundle:
        bundle_data()
    elif args.validate:
        validate_data()
    elif args.new_problem:
        generate_problem_template(args.chapter, args.title)
    else:
        # Default action: validate and bundle
        validate_data()
        bundle_data()


if __name__ == "__main__":
    main()
